seeds: 5

encdec:
  - 256
  - 512
  - &bn_layer 128
  - 512
  - 256
clustering_layer:
  - *bn_layer
  - 1024

dataset_path: /path/to/MSRCv1.pkl
batch_size: 210
stage_I_epochs: 300
stage_II_epochs: 350
stage_III_epochs: 400

train_fusion_start_epochs: 2500000
apply_reliable_pseudo_labels: true
pseudo_labels_k: 30
train_with_pseudo_labels_shuffle: true
cosine_neighbor_threshold: 0.5 # in range [-1,1]

pseudo_cca_loss: false
pseudo_cca_loss_lambda: 0.001
spectralnet_loss: false
spectralnet_loss_lambda: 0.1
use_decoder: true

lr: 1e-3

logs_dir: logs

trainer:
  accelerator: gpu
  devices: 1
  max_epochs: 1000
  deterministic: true
  logger: true
  log_every_n_steps: 10
  check_val_every_n_epoch: 10
  enable_checkpointing: false
  sync_batchnorm: true
  num_sanity_val_steps: 0
  enable_progress_bar: true
